export const UPDATE_STATUS_SCREEN = "UPDATE_STATUS_SCREEN";
export const GET_INFO_SCREEN = "GET_INFO_SCREEN";
export const UPDATE_TOURNAMENT = "UPDATE_TOURNAMENT";
export const UPDATE_PLAYOFF = "UPDATE_PLAYOFF";
export const UPDATE_PLAYOFF_SCREEN = "UPDATE_PLAYOFF_SCREEN";

export const LOG_OUT = "LOG_OUT";
