export const GET_PROFILE = "GET_PROFILE";
export const FAILED_GET_PROFILE = "FAILED_GET_PROFILE";
export const LOGIN = "LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const COMPLETE_ROUTE = "COMPLETE_ROUTE";
export const FAIL_REFRESH_TOKEN = "FAIL_REFRESH_TOKEN";
export const ADD_FREQUENT_ROUTE = "ADD_FREQUENT_ROUTE";
export const DELETE_FREQUENT_ROUTE_NOT_SAVE = "DELETE_FREQUENT_ROUTE_NOT_SAVE";
