export const GET_ALLOWED_TOURNAMENTS_QUALIFICATION =
  "GET_ALLOWED_TOURNAMENTS_QUALIFICATION";
export const GET_TEAMS_BY_TOURNAMENT = "GET_TEAMS_BY_TOURNAMENT";
export const GET_TOURNAMENT = "GET_TOURNAMENT";
export const PATCH_TOURNAMENT_QUALFICATION = "PATCH_TOURNAMENT_QUALFICATION";
export const GET_TOURNAMENT_QUALIFICATION = "GET_TOURNAMENT_QUALIFICATION";
export const SET_TEAM_SCREEN_UNVISIBLE = "SET_TEAM_SCREEN_UNVISIBLE";
export const GET_ALLOWED_TOURNAMENTS_DIRECT = "GET_ALLOWED_TOURNAMENTS_DIRECT";
export const GET_ALLOWED_TOURNAMENTS_ROUND = "GET_ALLOWED_TOURNAMENTS_ROUND";
export const GET_TOURNAMENT_DIRECT = "GET_TOURNAMENT_DIRECT";
export const GET_TOURNAMENT_ROUND = "GET_TOURNAMENT_ROUND";
export const GET_QUALIFICATION_RANKING = "GET_QUALIFICATION_RANKING";
