export const FETCHING_TRAININGS_DATA = "FETCHING_TRAININGS_DATA";
export const GET_USER_LEVEL = "GET_USER_LEVEL";
export const GET_TRAINING_SESSIONS = "GET_TRAINING_SESSIONS";
export const GET_EVENTS = "GET_EVENTS";
export const GET_LEVEL_EVENTS = "GET_LEVEL_EVENTS";
export const GET_COUNT_COMPLETED_EVENT_OF_TRAINING_SESSIONS =
  "GET_COUNT_COMPLETED_EVENT_OF_TRAINING_SESSIONS";
export const GET_COUNT_EVENT_OF_TRAINING_SESSIONS =
  "GET_COUNT_EVENT_OF_TRAINING_SESSIONS";
export const PUT_EVENTS = "PUT_EVENTS";
export const PUT_SESSION = "PUT_SESSION";
export const LEVEL_UP = "LEVEL_UP";
export const UPDATE_STATUS_TRAINING = "UPDATE_STATUS_TRAINING";
export const SAVE_OFFLINE_EVENTS = "SAVE_OFFLINE_EVENTS";
export const LOG_OUT = "LOG_OUT";
export const GET_QUIZ = "GET_QUIZ";
export const PUT_QUIZ = "PUT_QUIZ";
export const COMPLETE_QUIZ = "COMPLETE_QUIZ";
export const CHANGE_SCREEN_PROFILE = "CHANGE_SCREEN_PROFILE";
export const UPDATE_COUNTER_EVENT = "UPDATE_COUNTER_EVENT";
export const GET_SPECIAL_TRAINING_SESSIONS = "GET_SPECIAL_TRAINING_SESSIONS";
export const GET_SPECIAL_TRAINING_SESSIONS_SUBSCRIBED =
  "GET_SPECIAL_TRAINING_SESSIONS_SUBSCRIBED";
export const SUBSCRIBE_SPECIAL_TRAINING_SESSIONS =
  "SUBSCRIBE_SPECIAL_TRAINING_SESSIONS";
export const SET_NEW_ST_PIVOTS = "SET_NEW_ST_PIVOTS";
export const SET_COMPLETED_ST_PIVOTS = "SET_COMPLETED_ST_PIVOTS";
export const ADD_REDEEMED_REWARD = "ADD_REDEEMED_REWARD";

export const SAVE_ST_OFFLINE = "SAVE_ST_OFFLINE";
export const REMOVE_ST_OFFLINE = "REMOVE_ST_OFFLINE";

export const GET_COMPLETE_QUIZ = "GET_COMPLETE_QUIZ";

export const TOGGLE_ST_TEATRO = "TOGGLE_ST_TEATRO";
export const TOGGLE_ST_BALLARAK = "TOGGLE_ST_BALLARAK";
export const TOGGLE_ST_MUVTOGET = "TOGGLE_ST_MUVTOGET";
export const TOGGLE_ST_KALSA = "TOGGLE_ST_KALSA";
