export const FETCHING_DATA_FOLLOW = "FETCHING_DATA_FOLLOW";
export const FETCHING_DATA_FOLLOW_COMPLETE = "FETCHING_DATA_FOLLOW_COMPLETE";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const GET_FOLLOWER = "GET_FOLLOWER";
export const SET_SELECTION_FOLLOW = "SET_SELECTION_FOLLOW";

