export const CREATE_USER = "CREATE_USER";
export const UPDATE_STATE = "UPDATE_STATE";
export const FAIL_LOGIN = "FAIL_LOGIN";
export const START_LOGIN = "START_LOGIN";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const GET_MOBILITY_CAR_VALUES = "GET_MOBILITY_CAR_VALUES";
export const GET_MOBILITY_MOTO_VALUES = "GET_MOBILITY_MOTO_VALUES";
export const SAVE_BRANCH_TEMP_DATA = "SAVE_BRANCH_TEMP_DATA";
export const SET_REFERRAL_FROM_REGISTRATION = "SET_REFERRAL_FROM_REGISTRATION";
export const CLEAR_REFERRAL_FROM_REGISTRATION =
  "CLEAR_REFERRAL_FROM_REGISTRATION";
export const CLEAR_BRANCH_TEMP_DATA = "CLEAR_BRANCH_TEMP_DATA";
export const SET_CAR_SEGMENT = "SET_CAR_SEGMENT";
